### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by marina-cyber** [NifpdDD/time-series#7]
Поправьте определения понятий, которые вы используете.
Так - работа хорошего уровня.

**Comment by NifpdDD** [comment]
Каких именно понятий,я посмотрел, вроде все норм

**Comment by marina-cyber** [comment]
Про коинтеграцию и причинность. 

⁣Получить BlueMail для Android ​

На 20 янв. 2024 г., 21:55, в 21:55, Pavel ***@***.***> написал:п>Каких именно понятий,я посмотрел, вроде все норм

**Comment by NifpdDD** [comment]
Поправил

**Comment by NifpdDD** [comment]
Поправил

**Comment by marina-cyber** [comment]
Проект зачтен
